version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    container_name: server
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
       - ./server:/usr/src/app/server
  client:
    build:
      context: ./client
    ports:
      - "3001:3000"
    container_name: client
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
       - ./client:/usr/src/app/client